/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FeesRouteImport } from './routes/fees'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdmissionRouteImport } from './routes/admission'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedStoreRouteImport } from './routes/_authenticated/store'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedMyPurchasesRouteImport } from './routes/_authenticated/my-purchases'
import { Route as AuthenticatedLearnRouteImport } from './routes/_authenticated/learn'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedStoreCourseRouteImport } from './routes/_authenticated/store.$course'
import { Route as AuthenticatedLearnSlugRouteImport } from './routes/_authenticated/learn.$slug'
import { Route as AuthenticatedAdminStoreRouteImport } from './routes/_authenticated/admin.store'
import { Route as AuthenticatedAdminCoursesRouteImport } from './routes/_authenticated/admin.courses'
import { Route as AuthenticatedAdminAnnouncementsRouteImport } from './routes/_authenticated/admin.announcements'
import { Route as AuthenticatedStoreCourseSubjectRouteImport } from './routes/_authenticated/store.$course.$subject'
import { Route as AuthenticatedStoreCourseSubjectChapterRouteImport } from './routes/_authenticated/store.$course.$subject.$chapter'

const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FeesRoute = FeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionRoute = AdmissionRouteImport.update({
  id: '/admission',
  path: '/admission',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CoursesRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthenticatedStoreRoute = AuthenticatedStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyPurchasesRoute =
  AuthenticatedMyPurchasesRouteImport.update({
    id: '/my-purchases',
    path: '/my-purchases',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLearnRoute = AuthenticatedLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStoreCourseRoute =
  AuthenticatedStoreCourseRouteImport.update({
    id: '/$course',
    path: '/$course',
    getParentRoute: () => AuthenticatedStoreRoute,
  } as any)
const AuthenticatedLearnSlugRoute = AuthenticatedLearnSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AuthenticatedLearnRoute,
} as any)
const AuthenticatedAdminStoreRoute = AuthenticatedAdminStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCoursesRoute =
  AuthenticatedAdminCoursesRouteImport.update({
    id: '/courses',
    path: '/courses',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnnouncementsRoute =
  AuthenticatedAdminAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedStoreCourseSubjectRoute =
  AuthenticatedStoreCourseSubjectRouteImport.update({
    id: '/$subject',
    path: '/$subject',
    getParentRoute: () => AuthenticatedStoreCourseRoute,
  } as any)
const AuthenticatedStoreCourseSubjectChapterRoute =
  AuthenticatedStoreCourseSubjectChapterRouteImport.update({
    id: '/$chapter',
    path: '/$chapter',
    getParentRoute: () => AuthenticatedStoreCourseSubjectRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admission': typeof AdmissionRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRouteWithChildren
  '/downloads': typeof DownloadsRoute
  '/faq': typeof FaqRoute
  '/fees': typeof FeesRoute
  '/gallery': typeof GalleryRoute
  '/locations': typeof LocationsRoute
  '/resources': typeof ResourcesRoute
  '/results': typeof ResultsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonials': typeof TestimonialsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/learn': typeof AuthenticatedLearnRouteWithChildren
  '/my-purchases': typeof AuthenticatedMyPurchasesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/store': typeof AuthenticatedStoreRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/admin/store': typeof AuthenticatedAdminStoreRoute
  '/learn/$slug': typeof AuthenticatedLearnSlugRoute
  '/store/$course': typeof AuthenticatedStoreCourseRouteWithChildren
  '/store/$course/$subject': typeof AuthenticatedStoreCourseSubjectRouteWithChildren
  '/store/$course/$subject/$chapter': typeof AuthenticatedStoreCourseSubjectChapterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admission': typeof AdmissionRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRouteWithChildren
  '/downloads': typeof DownloadsRoute
  '/faq': typeof FaqRoute
  '/fees': typeof FeesRoute
  '/gallery': typeof GalleryRoute
  '/locations': typeof LocationsRoute
  '/resources': typeof ResourcesRoute
  '/results': typeof ResultsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonials': typeof TestimonialsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/learn': typeof AuthenticatedLearnRouteWithChildren
  '/my-purchases': typeof AuthenticatedMyPurchasesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/store': typeof AuthenticatedStoreRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/admin/store': typeof AuthenticatedAdminStoreRoute
  '/learn/$slug': typeof AuthenticatedLearnSlugRoute
  '/store/$course': typeof AuthenticatedStoreCourseRouteWithChildren
  '/store/$course/$subject': typeof AuthenticatedStoreCourseSubjectRouteWithChildren
  '/store/$course/$subject/$chapter': typeof AuthenticatedStoreCourseSubjectChapterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admission': typeof AdmissionRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRouteWithChildren
  '/downloads': typeof DownloadsRoute
  '/faq': typeof FaqRoute
  '/fees': typeof FeesRoute
  '/gallery': typeof GalleryRoute
  '/locations': typeof LocationsRoute
  '/resources': typeof ResourcesRoute
  '/results': typeof ResultsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonials': typeof TestimonialsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/learn': typeof AuthenticatedLearnRouteWithChildren
  '/_authenticated/my-purchases': typeof AuthenticatedMyPurchasesRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/store': typeof AuthenticatedStoreRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/_authenticated/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/_authenticated/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/_authenticated/admin/store': typeof AuthenticatedAdminStoreRoute
  '/_authenticated/learn/$slug': typeof AuthenticatedLearnSlugRoute
  '/_authenticated/store/$course': typeof AuthenticatedStoreCourseRouteWithChildren
  '/_authenticated/store/$course/$subject': typeof AuthenticatedStoreCourseSubjectRouteWithChildren
  '/_authenticated/store/$course/$subject/$chapter': typeof AuthenticatedStoreCourseSubjectChapterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admission'
    | '/auth'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/courses'
    | '/downloads'
    | '/faq'
    | '/fees'
    | '/gallery'
    | '/locations'
    | '/resources'
    | '/results'
    | '/sitemap.xml'
    | '/testimonials'
    | '/admin'
    | '/dashboard'
    | '/learn'
    | '/my-purchases'
    | '/profile'
    | '/store'
    | '/blog/$slug'
    | '/courses/$slug'
    | '/admin/announcements'
    | '/admin/courses'
    | '/admin/store'
    | '/learn/$slug'
    | '/store/$course'
    | '/store/$course/$subject'
    | '/store/$course/$subject/$chapter'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admission'
    | '/auth'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/courses'
    | '/downloads'
    | '/faq'
    | '/fees'
    | '/gallery'
    | '/locations'
    | '/resources'
    | '/results'
    | '/sitemap.xml'
    | '/testimonials'
    | '/admin'
    | '/dashboard'
    | '/learn'
    | '/my-purchases'
    | '/profile'
    | '/store'
    | '/blog/$slug'
    | '/courses/$slug'
    | '/admin/announcements'
    | '/admin/courses'
    | '/admin/store'
    | '/learn/$slug'
    | '/store/$course'
    | '/store/$course/$subject'
    | '/store/$course/$subject/$chapter'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/admission'
    | '/auth'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/courses'
    | '/downloads'
    | '/faq'
    | '/fees'
    | '/gallery'
    | '/locations'
    | '/resources'
    | '/results'
    | '/sitemap.xml'
    | '/testimonials'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/learn'
    | '/_authenticated/my-purchases'
    | '/_authenticated/profile'
    | '/_authenticated/store'
    | '/blog/$slug'
    | '/courses/$slug'
    | '/_authenticated/admin/announcements'
    | '/_authenticated/admin/courses'
    | '/_authenticated/admin/store'
    | '/_authenticated/learn/$slug'
    | '/_authenticated/store/$course'
    | '/_authenticated/store/$course/$subject'
    | '/_authenticated/store/$course/$subject/$chapter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdmissionRoute: typeof AdmissionRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  DownloadsRoute: typeof DownloadsRoute
  FaqRoute: typeof FaqRoute
  FeesRoute: typeof FeesRoute
  GalleryRoute: typeof GalleryRoute
  LocationsRoute: typeof LocationsRoute
  ResourcesRoute: typeof ResourcesRoute
  ResultsRoute: typeof ResultsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TestimonialsRoute: typeof TestimonialsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fees': {
      id: '/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof FeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admission': {
      id: '/admission'
      path: '/admission'
      fullPath: '/admission'
      preLoaderRoute: typeof AdmissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/_authenticated/store': {
      id: '/_authenticated/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof AuthenticatedStoreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-purchases': {
      id: '/_authenticated/my-purchases'
      path: '/my-purchases'
      fullPath: '/my-purchases'
      preLoaderRoute: typeof AuthenticatedMyPurchasesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learn': {
      id: '/_authenticated/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof AuthenticatedLearnRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/store/$course': {
      id: '/_authenticated/store/$course'
      path: '/$course'
      fullPath: '/store/$course'
      preLoaderRoute: typeof AuthenticatedStoreCourseRouteImport
      parentRoute: typeof AuthenticatedStoreRoute
    }
    '/_authenticated/learn/$slug': {
      id: '/_authenticated/learn/$slug'
      path: '/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof AuthenticatedLearnSlugRouteImport
      parentRoute: typeof AuthenticatedLearnRoute
    }
    '/_authenticated/admin/store': {
      id: '/_authenticated/admin/store'
      path: '/store'
      fullPath: '/admin/store'
      preLoaderRoute: typeof AuthenticatedAdminStoreRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/courses': {
      id: '/_authenticated/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AuthenticatedAdminCoursesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/announcements': {
      id: '/_authenticated/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AuthenticatedAdminAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/store/$course/$subject': {
      id: '/_authenticated/store/$course/$subject'
      path: '/$subject'
      fullPath: '/store/$course/$subject'
      preLoaderRoute: typeof AuthenticatedStoreCourseSubjectRouteImport
      parentRoute: typeof AuthenticatedStoreCourseRoute
    }
    '/_authenticated/store/$course/$subject/$chapter': {
      id: '/_authenticated/store/$course/$subject/$chapter'
      path: '/$chapter'
      fullPath: '/store/$course/$subject/$chapter'
      preLoaderRoute: typeof AuthenticatedStoreCourseSubjectChapterRouteImport
      parentRoute: typeof AuthenticatedStoreCourseSubjectRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnnouncementsRoute: typeof AuthenticatedAdminAnnouncementsRoute
  AuthenticatedAdminCoursesRoute: typeof AuthenticatedAdminCoursesRoute
  AuthenticatedAdminStoreRoute: typeof AuthenticatedAdminStoreRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnnouncementsRoute: AuthenticatedAdminAnnouncementsRoute,
  AuthenticatedAdminCoursesRoute: AuthenticatedAdminCoursesRoute,
  AuthenticatedAdminStoreRoute: AuthenticatedAdminStoreRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedLearnRouteChildren {
  AuthenticatedLearnSlugRoute: typeof AuthenticatedLearnSlugRoute
}

const AuthenticatedLearnRouteChildren: AuthenticatedLearnRouteChildren = {
  AuthenticatedLearnSlugRoute: AuthenticatedLearnSlugRoute,
}

const AuthenticatedLearnRouteWithChildren =
  AuthenticatedLearnRoute._addFileChildren(AuthenticatedLearnRouteChildren)

interface AuthenticatedStoreCourseSubjectRouteChildren {
  AuthenticatedStoreCourseSubjectChapterRoute: typeof AuthenticatedStoreCourseSubjectChapterRoute
}

const AuthenticatedStoreCourseSubjectRouteChildren: AuthenticatedStoreCourseSubjectRouteChildren =
  {
    AuthenticatedStoreCourseSubjectChapterRoute:
      AuthenticatedStoreCourseSubjectChapterRoute,
  }

const AuthenticatedStoreCourseSubjectRouteWithChildren =
  AuthenticatedStoreCourseSubjectRoute._addFileChildren(
    AuthenticatedStoreCourseSubjectRouteChildren,
  )

interface AuthenticatedStoreCourseRouteChildren {
  AuthenticatedStoreCourseSubjectRoute: typeof AuthenticatedStoreCourseSubjectRouteWithChildren
}

const AuthenticatedStoreCourseRouteChildren: AuthenticatedStoreCourseRouteChildren =
  {
    AuthenticatedStoreCourseSubjectRoute:
      AuthenticatedStoreCourseSubjectRouteWithChildren,
  }

const AuthenticatedStoreCourseRouteWithChildren =
  AuthenticatedStoreCourseRoute._addFileChildren(
    AuthenticatedStoreCourseRouteChildren,
  )

interface AuthenticatedStoreRouteChildren {
  AuthenticatedStoreCourseRoute: typeof AuthenticatedStoreCourseRouteWithChildren
}

const AuthenticatedStoreRouteChildren: AuthenticatedStoreRouteChildren = {
  AuthenticatedStoreCourseRoute: AuthenticatedStoreCourseRouteWithChildren,
}

const AuthenticatedStoreRouteWithChildren =
  AuthenticatedStoreRoute._addFileChildren(AuthenticatedStoreRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLearnRoute: typeof AuthenticatedLearnRouteWithChildren
  AuthenticatedMyPurchasesRoute: typeof AuthenticatedMyPurchasesRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedStoreRoute: typeof AuthenticatedStoreRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLearnRoute: AuthenticatedLearnRouteWithChildren,
  AuthenticatedMyPurchasesRoute: AuthenticatedMyPurchasesRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedStoreRoute: AuthenticatedStoreRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface CoursesRouteChildren {
  CoursesSlugRoute: typeof CoursesSlugRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesSlugRoute: CoursesSlugRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AdmissionRoute: AdmissionRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRouteWithChildren,
  DownloadsRoute: DownloadsRoute,
  FaqRoute: FaqRoute,
  FeesRoute: FeesRoute,
  GalleryRoute: GalleryRoute,
  LocationsRoute: LocationsRoute,
  ResourcesRoute: ResourcesRoute,
  ResultsRoute: ResultsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TestimonialsRoute: TestimonialsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
